default_platform(:android)

platform :android do
  desc "Lane for Android App Distribution" 
  lane :firebase_distribution do
    # Clean the Flutter project
    sh "flutter clean"
    
    # Build the APK in release mode
    sh "flutter build apk --release --no-tree-shake-icons"
    
    # Distribute the APK via Firebase
    firebase_app_distribution(
      app: "1:670184640142:android:a3c6f6b82dfbf6635583df",
      firebase_cli_token: "",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "yo7sef1980@gmail.com",
      release_notes: "Release notes", # Read release notes from a file
    )
  end
end
