name: github-actions-android

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    distribution_to_firebase:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout the code 
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: 17
            distribution: 'temurin'

        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.3.7
            bundler-cache: true
            working-directory: android
        
        - name: build and distribute App
          env: 
            FIREBASE_TOKEN: ${{ secrets.firebase_cli_token }}
          run: |
            bundle exec fastlane distribute_to_firebase
          working-directory: android   